# Generated by Django 5.2.1 on 2025-05-30 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailotp',
            name='name',
        ),
    ]
