# Generated by Django 5.2.1 on 2025-05-25 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_emailotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailotp',
            name='valid_until',
            field=models.DateTimeField(),
        ),
    ]
