# Generated by Django 5.2.1 on 2025-05-27 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_customuser_reset_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='time_token_set',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
